[package]
name = "octothorpe"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
http = "1.0"
url = "2.5.0"
bytes = "1"
reqwest = { version = "0.11", features = ["json", "blocking"] }